---
baseurl         : "http://hgfischer.org/"
title           : "Steampunk Gopher"
copyright       : "Copyright (c) 1997-2014, Herbert G. Fischer; all rights reserved."
MetaDataFormat  : "yaml"
disqusShortname : "hgfischer"

params:
    AuthorName: "Herbert G. Fischer"

indexes:
    tag: "tags"
