---
baseurl: "http://hgfischer.org/"
title: "Memory Leak"
copyright: "Copyright (c) 1997-2014, Herbert G. Fischer; all rights reserved."
MetaDataFormat: "yaml"
disqusShortname: "hgfischer"
params:
    Author: "Herbert Fischer"
indexes:
    tag: "tags"
